version: "3.9"

services:
  database:
    container_name: postgres
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

#version: "3.9"
#
#services:
#  database:
#    container_name: api-dev-db
#    image: mysql:8.0
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_DATABASE: api
#      MYSQL_USER: symfony
#      MYSQL_PASSWORD: symfony
#    ports:
#      - '4306:3306'
